### PR TITLE
Allows for responding to software token challenge

### PR DESCRIPTION
**Pull request by jherbert**
*Issue #, if available:* #55 

*Description of changes:* Hey @NGL321, I just happened to need this same feature that was in this issue.

Do let me know if I'm missing anything in this pull request.

Thanks!

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jherbert** [comment]
@normj Any chance we can get a second review on this one?

Also what is the release schedule like on this project?

Thank you!

**Comment by tavisca-anjoshi** [comment]
Hi @NGL321/@normj,
Any estimated time for this PR to merge in master?

**Comment by iainb123** [comment]
Keen to use this too - any chance of this going in soon?

**Comment by normj** [comment]
We merged in PR https://github.com/aws/aws-sdk-net-extensions-cognito/pull/58 which added support for the software token. That PR was released as part of version 2.1.0.

**Pull request closed without merging**
